name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]  # Specify the Node.js version you want to use

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2  # Updated to version 2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          cd server
          npm install
          cd ../client  # Move back to the root directory
          npm install
      - name: Build
        run: |
          cd client
          npm run build
